// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqZQADYdVn8xsHt1FKAWcvszn89kkczrk',
    appId: '1:313511075030:web:c9d929718085bde5f1bd77',
    messagingSenderId: '313511075030',
    projectId: 'link-ecommerce',
    authDomain: 'link-ecommerce.firebaseapp.com',
    storageBucket: 'link-ecommerce.firebasestorage.app',
    measurementId: 'G-ZRHXX33V60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9m6SINKSBts5evgYPqaqBt6qUvAvY3_c',
    appId: '1:313511075030:android:accab7a4b88669bff1bd77',
    messagingSenderId: '313511075030',
    projectId: 'link-ecommerce',
    storageBucket: 'link-ecommerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP86DQg_OZrxP1Xy8tSl4ddXV0mUWwg6k',
    appId: '1:313511075030:ios:8bce0bdf307fc4e1f1bd77',
    messagingSenderId: '313511075030',
    projectId: 'link-ecommerce',
    storageBucket: 'link-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.linkFlutterEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP86DQg_OZrxP1Xy8tSl4ddXV0mUWwg6k',
    appId: '1:313511075030:ios:8bce0bdf307fc4e1f1bd77',
    messagingSenderId: '313511075030',
    projectId: 'link-ecommerce',
    storageBucket: 'link-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.linkFlutterEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqZQADYdVn8xsHt1FKAWcvszn89kkczrk',
    appId: '1:313511075030:web:473eb6d896399989f1bd77',
    messagingSenderId: '313511075030',
    projectId: 'link-ecommerce',
    authDomain: 'link-ecommerce.firebaseapp.com',
    storageBucket: 'link-ecommerce.firebasestorage.app',
    measurementId: 'G-E552SKPX3D',
  );
}
